spring.application.name=banking-api

# H2 ?????? ?? ??
spring.datasource.url=jdbc:h2:mem:bankingdb

# H2 ????
spring.datasource.driver-class-name=org.h2.Driver

# ??? ? Entity? ???? ??? ??/??
spring.jpa.hibernate.ddl-auto=update

# ?????? H2 Console ??
spring.h2.console.enabled=true

# sql? ???? ??? ???? ?? ???? ?? ?? ??
spring.jpa.show-sql=true